# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ajl.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1141, 865)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 991, 561))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../Users/Aviral singh halsi/Desktop/inventory-management-blog.png"))
        self.label.setObjectName("label")
        self.bb = QtWidgets.QPushButton(self.centralwidget)
        self.bb.setGeometry(QtCore.QRect(700, 170, 93, 51))
        self.bb.setObjectName("bb")
        self.le = QtWidgets.QLineEdit(self.centralwidget)
        self.le.setGeometry(QtCore.QRect(542, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.le.setFont(font)
        self.le.setText("")
        self.le.setObjectName("le")
        self.le1 = QtWidgets.QLineEdit(self.centralwidget)
        self.le1.setGeometry(QtCore.QRect(710, 80, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.le1.setFont(font)
        self.le1.setObjectName("le1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(720, 260, 341, 261))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.l2.setFont(font)
        self.l2.setText("")
        self.l2.setObjectName("l2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 550, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(100, 510, 55, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l3.setFont(font)
        self.l3.setText("")
        self.l3.setObjectName("l3")
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(190, 580, 181, 91))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(680, 660, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(110, 10, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.l4.setFont(font)
        self.l4.setText("")
        self.l4.setObjectName("l4")
        self.le2 = QtWidgets.QLineEdit(self.centralwidget)
        self.le2.setGeometry(QtCore.QRect(810, 80, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le2.setFont(font)
        self.le2.setObjectName("le2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 40, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 30, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(830, 30, 53, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(910, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.le3 = QtWidgets.QLineEdit(self.centralwidget)
        self.le3.setGeometry(QtCore.QRect(900, 80, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le3.setFont(font)
        self.le3.setObjectName("le3")
        self.tot = QtWidgets.QLabel(self.centralwidget)
        self.tot.setGeometry(QtCore.QRect(840, 560, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tot.setFont(font)
        self.tot.setText("")
        self.tot.setObjectName("tot")
        self.prof = QtWidgets.QLabel(self.centralwidget)
        self.prof.setGeometry(QtCore.QRect(850, 660, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.prof.setFont(font)
        self.prof.setText("")
        self.prof.setObjectName("prof")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1141, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.bb.clicked.connect(self.aa)
        self.bb.clicked.connect(self.total)
        self.c=0
        self.total=0
        self.cp=0
        self.b2.clicked.connect(self.clear)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bb.setText(_translate("MainWindow", "Add"))
        self.label_2.setText(_translate("MainWindow", "Total"))
        self.b2.setText(_translate("MainWindow", "sell"))
        self.label_3.setText(_translate("MainWindow", "Profit:"))
        self.label_4.setText(_translate("MainWindow", "Name"))
        self.label_5.setText(_translate("MainWindow", "Quantity"))
        self.label_6.setText(_translate("MainWindow", "CP"))
        self.label_7.setText(_translate("MainWindow", "sp"))


    def aa(self):
        self.c=self.c+1
        quan=self.le1.text()
        sp=self.le3.text()

        if self.c==1:
            a=self.le.text()
            self.l2.setText("{}-->{}".format(a,int(quan)*int(sp)))
        else:
            b=self.l2.text()
            a=self.le.text()
            self.l2.setText("{}\n{}-->{}".format(b,a,int(quan)*int(sp)))

    def total(self):
        q=self.le1.text()
        sp=self.le3.text()
        cost=self.le2.text()
        self.total=self.total+int(q)*int(sp)
        self.cp=self.cp+int(q)*int(cost)
        self.tot.setText("{}".format(self.total))
        self.prof.setText("{}".format(self.total-self.cp))

    def clear(self):
        self.tot.setText("")
        self.prof.setText("")
        self.l2.setText("")




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
